#ifndef __GAMEMAIN_H__
#define __GAMEMAIN_H__

#include "Console.h"

// color
#define FOREGROUND_BLUE	1
#define FOREGROUND_GREEN	2
#define FOREGROUND_RED	4
#define FOREGROUND_INTENSITY	8
#define BACKGROUND_BLUE	16
#define BACKGROUND_GREEN	32
#define BACKGROUND_RED	64
#define BACKGROUND_INTENSITY	128
#define ENABLE_ECHO_INPUT 4

enum COLOR {
         BLACK      = 0,
         GREY       = FOREGROUND_BLUE+FOREGROUND_GREEN+FOREGROUND_RED,
         WHITE      = FOREGROUND_INTENSITY+GREY,
  INTENS_BLUE       = FOREGROUND_INTENSITY+FOREGROUND_BLUE,
  INTENS_GREEN      = FOREGROUND_INTENSITY+FOREGROUND_GREEN,
  INTENS_RED        = FOREGROUND_INTENSITY+FOREGROUND_RED,
         CYAN       = FOREGROUND_BLUE+FOREGROUND_GREEN,
  INTENS_CYAN       = FOREGROUND_INTENSITY+CYAN,
         MAGENTA    = FOREGROUND_RED+FOREGROUND_BLUE,
  INTENS_MAGENTA    = FOREGROUND_INTENSITY+MAGENTA,
         YELLOW     = FOREGROUND_RED+FOREGROUND_GREEN,
  INTENS_YELLOW     = FOREGROUND_INTENSITY+YELLOW,
         BG_BLACK   = 0,
         BG_GREY    = BACKGROUND_BLUE+BACKGROUND_GREEN+BACKGROUND_RED,
         BG_WHITE   = BACKGROUND_INTENSITY+BG_GREY,
  BG_INTENS_BLUE    = BACKGROUND_INTENSITY+BACKGROUND_BLUE,
  BG_INTENS_GREEN   = BACKGROUND_INTENSITY+BACKGROUND_GREEN,
  BG_INTENS_RED     = BACKGROUND_INTENSITY+BACKGROUND_RED,
         BG_CYAN    = BACKGROUND_BLUE+BACKGROUND_GREEN,
  BG_INTENS_CYAN    = BACKGROUND_INTENSITY+BG_CYAN,
         BG_MAGENTA = BACKGROUND_RED+BACKGROUND_BLUE,
  BG_INTENS_MAGENTA = BACKGROUND_INTENSITY+BG_MAGENTA,
         BG_YELLOW  = BACKGROUND_RED+BACKGROUND_GREEN,
  BG_INTENS_YELLOW  = BACKGROUND_INTENSITY+BG_YELLOW
};

// key codes
#define VK_SPACE 32
#define VK_UP 72
#define VK_DOWN 80
#define VK_LEFT 75
#define VK_RIGHT 77
#define VK_Q 113

// user graphics
#define PLAYER "Å°" 
#define BULLET_STR "Åb"
#define MONSTER_STR "Çƒ" 
#define MON_BULLET_STR "ÅE"

// item
#define BULLET_MAX 20
#define MON_MAX 1
#define MON_BULLET_MAX 1

// bullet struct
struct BULLET {
	int x;
	int y;
	int flag;
};

struct MONSTER {
	int x;
	int y;
	int dx;
	int dy;
	int flag;
};

void attackcheck();
void monstermake();
void monstermove();
void bulletshoot();
void bulletmove();
void gameinit();
void gameloop();
int endcheck();
void keycheck();
void draw();
void fps();
double fpscount();
void gamewait();
int GetNowCount();

#endif // __GAMEMAIN_H__
